server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Subhasis@123
    url: jdbc:mysql://localhost:3306/Spring_Security
    username: root
  jpa:
    show-sql: true
